name: Build Android APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: npm install --legacy-peer-deps
        
    - name: Install Expo CLI
      run: npm install -g @expo/cli
      
    - name: Debug environment
      run: |
        node --version
        npm --version
        java -version
        echo "Android SDK: $ANDROID_SDK_ROOT"
        ls -la
        
    - name: Create basic eas.json
      run: |
        cat > eas.json << 'EOF'
        {
          "cli": {
            "version": ">= 13.2.0"
          },
          "build": {
            "preview": {
              "android": {
                "buildType": "apk"
              }
            }
          }
        }
        EOF
        
    - name: Try prebuild
      run: npx expo prebuild --platform android --clear --no-install
        
    - name: List android directory
      run: |
        if [ -d "android" ]; then
          echo "Android directory exists"
          ls -la android/
        else
          echo "Android directory not found"
          exit 1
        fi
        
    - name: Make gradlew executable
      run: chmod +x android/gradlew
      
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleRelease --no-daemon --stacktrace
        
    - name: Find APK
      run: find . -name "*.apk" -type f
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: android/app/build/outputs/apk/release/app-release.apk
        name: VerseNotes ${{ github.ref_name }}
        body: |
          Android APK for VerseNotes ${{ github.ref_name }}
          
          Download the APK below and install on your Android device.
          
          Requirements:
          - Android 13 or higher
          - Enable "Unknown Sources" in settings
          
          Features:
          - Bible study with WEB translation
          - Note-taking with rich text
          - Backup/export functionality
          - Optimized for Daylight DC1 tablet
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 